import { Inter,Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ weight:['100','500','700','900'],subsets: ["latin"] });

export const metadata = {
  title: {
    default:"Next Hero",
    template:"%s | Next Hero"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
       <Navbar/>
        <div>
          {children}
        </div>
        <footer className="bg-red-400 text-center py-2">
          @All rights reserved for <span className="text-cyan-400">next-hero.com</span>
        </footer>
      </body>
    </html>
  );
}
